"""Word 文档生成器 - 将 Agent 回答内容转换为格式规范的 Word 文档"""

from datetime import datetime
from io import BytesIO
from pathlib import Path
from typing import Optional

from src.config import Settings, logger

OUTPUT_DIR = Settings.PROJECT_ROOT / "data" / "outputs"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)


def generate_word_document(
    content: str,
    title: str = "问答结果",
    question: str = "",
    filename: str = "",
) -> str:
    """生成 Word 文档并返回文件路径"""
    try:
        from docx import Document
        from docx.shared import Inches, Pt, RGBColor
        from docx.enum.text import WD_ALIGN_PARAGRAPH
    except ImportError:
        raise RuntimeError("python-docx not installed")

    doc = Document()

    # 设置默认字体
    style = doc.styles["Normal"]
    font = style.font
    font.name = "Microsoft YaHei"
    font.size = Pt(11)

    # 标题
    title_para = doc.add_heading(title, level=0)
    title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

    # 元信息
    meta = doc.add_paragraph()
    meta.alignment = WD_ALIGN_PARAGRAPH.CENTER
    meta_run = meta.add_run(f"生成时间: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    meta_run.font.size = Pt(9)
    meta_run.font.color.rgb = RGBColor(128, 128, 128)

    doc.add_paragraph()  # 空行

    # 用户问题
    if question:
        q_heading = doc.add_heading("用户提问", level=2)
        q_para = doc.add_paragraph(question)
        q_para.style = doc.styles["Quote"]
        doc.add_paragraph()

    # AI 回答
    a_heading = doc.add_heading("AI 回答", level=2)
    # 按段落分割内容
    paragraphs = content.split("\n")
    for line in paragraphs:
        line = line.strip()
        if not line:
            doc.add_paragraph()
            continue
        if line.startswith("## ") or line.startswith("### "):
            level = 2 if line.startswith("## ") else 3
            doc.add_heading(line.lstrip("# "), level=level)
        elif line.startswith("- ") or line.startswith("* "):
            doc.add_paragraph(line[2:], style="List Bullet")
        elif line.startswith("1. ") or line.startswith("2. "):
            doc.add_paragraph(line[3:], style="List Number")
        elif line.startswith("```"):
            continue
        elif line.startswith("|"):
            continue
        else:
            doc.add_paragraph(line)

    # 页脚
    doc.add_paragraph()
    footer = doc.add_paragraph()
    footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
    footer_run = footer.add_run("--- 由学习辅助系统 AI 生成 ---")
    footer_run.font.size = Pt(8)
    footer_run.font.color.rgb = RGBColor(160, 160, 160)

    # 保存
    safe_filename = filename or f"answer_{datetime.now().strftime('%Y%m%d_%H%M%S')}.docx"
    file_path = OUTPUT_DIR / safe_filename
    doc.save(str(file_path))

    logger.info(f"Word document generated | path={file_path} chars={len(content)}")
    return str(file_path)


def generate_word_bytes(content: str, title: str = "Q&A Result", question: str = "") -> bytes:
    """生成 Word 文档并返回字节流"""
    try:
        from docx import Document
        from docx.shared import Pt, RGBColor
        from docx.enum.text import WD_ALIGN_PARAGRAPH
    except ImportError:
        raise RuntimeError("python-docx not installed")

    doc = Document()

    style = doc.styles["Normal"]
    font = style.font
    font.name = "Microsoft YaHei"
    font.size = Pt(11)

    title_para = doc.add_heading(title, level=0)
    title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

    meta = doc.add_paragraph()
    meta.alignment = WD_ALIGN_PARAGRAPH.CENTER
    meta_run = meta.add_run(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    meta_run.font.size = Pt(9)
    meta_run.font.color.rgb = RGBColor(128, 128, 128)

    doc.add_paragraph()

    if question:
        doc.add_heading("Question", level=2)
        q_para = doc.add_paragraph(question)
        q_para.style = doc.styles["Quote"]
        doc.add_paragraph()

    doc.add_heading("Answer", level=2)
    paragraphs = content.split("\n")
    for line in paragraphs:
        line = line.strip()
        if not line:
            doc.add_paragraph()
            continue
        if line.startswith("## ") or line.startswith("### "):
            level = 2 if line.startswith("## ") else 3
            doc.add_heading(line.lstrip("# "), level=level)
        elif line.startswith("- ") or line.startswith("* "):
            doc.add_paragraph(line[2:], style="List Bullet")
        elif line.startswith("1. "):
            doc.add_paragraph(line[3:], style="List Number")
        elif line.startswith("```"):
            continue
        elif line.startswith("|"):
            continue
        else:
            doc.add_paragraph(line)

    doc.add_paragraph()
    footer = doc.add_paragraph()
    footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
    footer_run = footer.add_run("--- Generated by Learning Assistant AI ---")
    footer_run.font.size = Pt(8)
    footer_run.font.color.rgb = RGBColor(160, 160, 160)

    buf = BytesIO()
    doc.save(buf)
    buf.seek(0)
    return buf.getvalue()
